### ISSUE TITLE
"gulp build" doesn't produce minified CSS

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/web-style-guide#12]
`gulp build` should be producing `ubuntu-styles.css` and `ubuntu-styles.css.min`.

I can see some code which looks like it should do that in [gulpfile.js](/ubuntudesign/web-style-guide/blob/7a3f776ed6e30b757e9eb7e6337d744445b68cb9/gulpfile.js#L48) but it's not working.

**Comment by anthonydillon** [comment]
Tested and ```gulp build``` is creating core-print.css, core-print.min.css, ubuntu-styles.css and ubuntu-styles.min.css.
