### ISSUE TITLE
No install instructions

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/web-style-guide#67]
It'll be helpful to anyone who needs to install ruby/sass/etc to fix a bug or build/rebuild as part of a deploy process if there are detailed install instructions in either README or INSTALL

**Comment by nottrobin** [comment]
I'd prefer if we didn't make the README really long. The READMEs in some of those other projects like blues_browser or the maas project are just really hard to read. I think the README should be a short introduction to get people up and running in the most standard use-case.

After my new pull request (#75) most people will be able to install all dependencies with simply `npm install`. If this doesn't work for anyone, we should fix the script so it does. Writing a README to cover those special cases will be really complex, 'cos at that point we're basically writing a debugging guide for npm, gem and gulp on all systems.

**Comment by nottrobin** [comment]
We could include a `HACKING.md` if we really need complex specialist instructions in the repository.

**Comment by anthonydillon** [comment]
@nottrobin I agree. Lets update the README to include just the ```npm install``` with a link to support or bugs if there is an issue.

**Comment by nottrobin** [comment]
@anthonydillon the former has been done: https://github.com/ubuntudesign/web-style-guide#getting-started. So you'd like a section in the README about how to report bugs?

**Comment by anthonydillon** [comment]
@nottrobin I think it would be nice to have a link near the install command for people to use (even to the issues) if there is any errors.

**Comment by nottrobin** [comment]
I've created #77 and #76. Closing this issue now.
